name: Send mail

on:
  schedule:
    - cron: 0 11 * * *
    - cron: 10 4 * * *

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: send mail
        run: |
          npm install
          npm run send
