name: Send mail

on:
  schedule:
  - cron: 47 18 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: send mail
      run: |
        npm install
        npm run send
