name: Send mail

on:
  schedule:
    - cron: 0 11 * * *

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: ./
      - name: send mail
        run: |
          npm install
          npm run send
