name: Send mail

on:
  schedule:
    - cron: "*/5 * * * *"

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: ianwalter/puppeteer@v2.0.0
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: false
        with:
          args: npm install
      - name: Send mail
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: npm run send
